### ISSUE TITLE
Efeitos sonoros e implementação. 

### ISSUE THREAD

**Issue by dev-waldomiro** [dev-u/QuizENA#14]
- [x] Um som para o acerto e um para o erro.
 - [x] Um som para os dez segundos finais.
    - O efeito deve ser como um apito para cada segundo.

- Implementar no jogo
   - [X] Som acerto
   - [X] Som erro
   - [x]  Música tela de inicio
   - [x] Música durante partida
   - [x] Som segundos finais (PENDENTE)

**Comment by grodriguesc** [comment]
Musica tensa para o quiz, talvez não seja necesssário som de apito, olhar musica no Drive e dar o aval. @dev-waldomiro.

**Comment by grodriguesc** [comment]
Escolher entre os sons de acerto no Drive, @dev-waldomiro .

**Comment by hugouchoasborges** [comment]
https://github.com/dev-u/QuizENA/pull/43
