### ISSUE TITLE
Plano de fundo: tela inicial e final

### ISSUE THREAD

**Issue by dev-waldomiro** [dev-u/QuizENA#39]
- [x] Criar uma tela de fundo para o início do jogo.
   - Deve conter referências em geral de quadrinhos, animes e jogos sem atrapalhar o texto.
   - Os blocos de texto (ranking, nome) devem ter um fundo de cor destacado. 

 - [x] Criar uma tela de fundo para o final do jogo. 
    - Deve conter o logo do ENA e da Dev U.
    - Fundo com cor destacada para a pontuação do jogador.

**Comment by hugouchoasborges** [comment]
https://github.com/dev-u/QuizENA/pull/44
